export const PRODUCTION_LIST_REQUEST = 'PRODUCTION_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILS = 'PRODUCT_LIST_FAILS'


export const PRODUCTION_DETAILS_REQUEST = 'PRODUCTION_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILS = 'PRODUCT_DETAILS_FAILS'